import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  const { data } = api.posts.getAll.useQuery();
  console.log('api::: ', api)

  console.log('data::: ', data);

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          {/* {user.isSignedIn ? <SignOutButton /> : <SignInButton mode="modal" />} */}
          {user.isSignedIn ? <SignOutButton /> : <SignInButton mode="modal" />}
        </div>
        <div>
          {data?.map((post) => (<div key={post.id}>{post.content}</div>))}
        </div>



      </main>
    </>
  );
};

export default Home;
